name: prayer
description: "A new Flutter project."
publish_to: 'none'          # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # ─── Localization ──────────────────────────────────────────────
  flutter_localizations:     # 115‑language widget translations
    sdk: flutter             # ← MUST come from the Flutter SDK
  intl: any                  # ICU date/number/plural handling
  # ────────────────────────────────────────────────────────────────

  cupertino_icons: ^1.0.8
  provider: ^6.0.3
  geolocator: ^9.0.2
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  adhan: ^2.0.0+1
  adhkar: ^0.0.1
  shared_preferences: ^2.5.1
  audioplayers: ^6.1.1
  geocoding: ^2.0.0
  percent_indicator: ^4.2.2
  confetti: ^0.7.0
  flutter_compass: ^0.8.1
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  sensors_plus: ^6.1.1
  quran: ^1.0.0
  share_plus: ^10.1.4
  fl_chart: ^0.66.0
  permission_handler: ^12.0.0+1
  flutter_heatmap_calendar: ^1.0.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ─── Flutter‑specific section ────────────────────────────────────
flutter:
  generate: true             # ← Tells Flutter to run gen‑l10n
  uses-material-design: true

  assets:
    - images/compass.png
    - assets/adhan/
    - assets/adhan/adhan_normal.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
