name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Flutter doctor
        run: flutter doctor -v
          
      - name: Get Flutter dependencies
        run: flutter pub get
      
      - name: Generate localization files
        run: flutter gen-l10n
        
      - name: Verify generated files
        run: |
          echo "Checking if localization files were generated..."
          ls -la .dart_tool/flutter_gen/gen_l10n/ || echo "gen_l10n directory not found"
          find . -name "app_localizations.dart" -type f || echo "app_localizations.dart not found"
          
      - name: Clean Flutter build
        run: flutter clean
        
      - name: Get Flutter dependencies again
        run: flutter pub get
        
      - name: Regenerate localization files
        run: flutter gen-l10n

      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods dependencies
        run: pod install
        working-directory: ios

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move app to Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release" 